name: CI

on:
  push:
    branches: '**'
  pull_request:

jobs:
  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: crate-ci/typos@v1.39.0

  pruefen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: lts/Jod
          cache: npm

      - name: Build plugin
        run: |
          npm ci
          npm run build

      - name: Check data
        run: npm run pruefen
